### ISSUE TITLE
Inline text and formulas while using the template

### ISSUE THREAD

**Issue by Firas-24** [augustebaum/epfl-thesis-typst#1]
I'm using EPFL template in typst and when using math mode, I cannot write formulas and text in the same line, it automatically write in a new line. I do not have this problem when disabling this template. I added a screenshot as an example. The rule from the template is in located in line 199.
![inline-text-and-formulas-while-using-a-template-v0-hwt71azu84ad1](https://github.com/augustebaum/epfl-thesis-typst/assets/144046206/fff1e721-a541-4405-9074-b444c2757708)

**Comment by augustebaum** [comment]
This should be fixed in version 0.1.1. Just need to go through the Typst publishing process now. Thanks for your patience!
